language: ruby
sudo: false
rvm:
  - 2.6
  - 2.7
  - 3.0
install:
  - rm -f Gemfile.lock
  - gem install bundler
  - bundle install
script:
  - srb typecheck
  - bundle exec rubocop
  - bundle exec rspec
